export const restaurants = {
  Chipotle: {
    name: "Chipotle",
    distance: 1.5,
    rating: 3.5,
    cost: 2,
    cuisines: ["Mexican"],
    categories: ["Fast food", "Bowl"],
    safeRestrictions: ["nuts", "dairy", "vegan", "vegetarian", "soy", "fish"],
    ammenities: ["Apple Pay", "Android Pay", "Mobile Order", "Takeout"],
  },
  Cava: {
    name: "Cava",
    distance: 2.3,
    rating: 3.8,
    cost: 2,
    cuisines: ["Mediterranean"],
    categories: ["Fast food", "Bowl"],
    safeRestrictions: ["nuts", "dairy", "vegan", "vegetarian", "soy", "fish"],
    ammenities: ["Apple Pay", "Android Pay", "Mobile Order", "Takeout"],
  },
  HiroNori: {
    name: "HiroNori Craft Ramen",
    distance: 3.1,
    rating: 4.4,
    cost: 3,
    cusines: ["Japanese"],
    categories: ["Restaurant", "Ramen"],
    safeRestrictions: ["nuts", "dairy", "vegetarian"],
    ammenities: ["Apple Pay", "Android Pay"],
  },
  HaiDiLao: {
    name: "HaiDiLao HotPot",
    distance: 2.0,
    rating: 3.9,
    cost: 3,
    cusines: ["Chinese"],
    categories: ["Restaurant", "Hotpot", "Soup"],
    safeRestrictions: ["nuts", "dairy", "vegetarian", "fish"],
    ammenities: ["Apple Pay", "Android Pay"],
  },
  ShariNori: {
    name: "ShariNori",
    distance: 4.1,
    rating: 4.1,
    cost: 3,
    cusines: ["Japanese"],
    categories: ["Restaurant", "Sushi"],
    safeRestrictions: ["nuts", "dairy", "vegetarian", "fish"],
    ammenities: ["Apple Pay", "Android Pay"],
  },
  NepCafe: {
    name: "Nep Cafe",
    distance: 4.5,
    rating: 4.6,
    cost: 3,
    cusines: ["Vietnamese"],
    categories: ["Cafe", "Breakfast", "Brunch"],
    safeRestrictions: ["nuts", "dairy", "fish"],
    ammenities: ["Apple Pay", "Android Pay", "Takeout"],
  },
  HalalGuys: {
    name: "The Halal Guys",
    distance: 3.7,
    rating: 3.8,
    cost: 2,
    cusines: ["Middle Eastern"],
    categories: ["Fast food", "Bowl", "Halal"],
    safeRestrictions: ["nuts", "dairy", "fish", "halal", "soy"],
    ammenities: ["Apple Pay", "Android Pay", "Takeout"],
  },
  TaqueriaAyutlaOaxaca: {
    name: "Taqueria Ayutla Oaxaca",
    distance: 2.2,
    rating: 4.3,
    cost: 1,
    cusines: ["Mexican"],
    categories: ["Food truck", "Tacos"],
    safeRestrictions: ["nuts", "dairy", "fish", "soy"],
    ammenities: ["Cash only", "Takeout"],
  },
  ElPolloLoco: {
    name: "El Pollo Loco",
    distance: 1.6,
    rating: 3.3,
    cost: 1,
    cusines: ["Mexican"],
    categories: ["Fast food", "Chicken"],
    safeRestrictions: ["nuts", "dairy", "fish", "soy"],
    ammenities: ["Apple Pay", "Android Pay", "Mobile order", "Drive thru"],
  },
  RaisingCanes: {
    name: "Raising Canes",
    distance: 1.6,
    rating: 4.0,
    cost: 1,
    cusines: ["American"],
    categories: ["Fast food", "Chicken"],
    safeRestrictions: ["nuts", "fish", "soy"],
    ammenities: ["Apple Pay", "Android Pay", "Mobile order", "Drive thru"],
  },
};
